---

- name: Enable firewalld
  service: name=firewalld state=started enabled=yes

- name: Open port 24007 (GlusterFS daemon)
  firewalld: port=24007/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Open port 24008 (GlusterFS management)
  firewalld: port=24008/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Open port 2222 (GlusterFS sshd)
  firewalld: port=2222/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Open ports 49152-49251 (GlusterFS bricks)
  firewalld: port=49152-49251/tcp zone=trusted permanent=true state=enabled immediate=true